apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: prime-deploy
  name: prime-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: prime-deploy
  type: NodePort
status:
  loadBalancer: {}